name: Check Configurations

on:
  workflow_dispatch:

jobs:
  run:
    uses: rafaelscone/meuip/.github/workflows/check-sonar.yaml@main
    permissions:
      contents: write
      id-token: write
    secrets: inherit